ALTER TABLE `property_master`.`prop_features` MODIFY COLUMN `bed_Rooms` VARCHAR(20) DEFAULT NULL,
 MODIFY COLUMN `bath_Rooms` VARCHAR(20) DEFAULT NULL,
 MODIFY COLUMN `avail_Floor` VARCHAR(20) DEFAULT NULL,
 MODIFY COLUMN `balconies` VARCHAR(20) DEFAULT NULL;