package com.sample.client;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI IBM 2.0_03-06/12/2007
 * 07:44 PM(Raja)-fcs Generated source version: 2.0
 * 
 */
@WebService(name = "CalculatorDelegate", targetNamespace = "http://www.example.org/calculatorservice/")
public interface CalculatorDelegate {

	/**
	 * 
	 * @param arg0
	 * @param arg1
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://www.example.org/calculatorservice/")
	@RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/calculatorservice/", className = "com.sample.impl.jaxws.Add")
	@ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/calculatorservice/", className = "com.sample.impl.jaxws.AddResponse")
	public int add(@WebParam(name = "arg0", targetNamespace = "http://www.example.org/calculatorservice/")
	int arg0, @WebParam(name = "arg1", targetNamespace = "http://www.example.org/calculatorservice/")
	int arg1);

	/**
	 * 
	 * @param arg0
	 * @param arg1
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://www.example.org/calculatorservice/")
	@RequestWrapper(localName = "subtract", targetNamespace = "http://www.example.org/calculatorservice/", className = "com.sample.impl.jaxws.Subtract")
	@ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://www.example.org/calculatorservice/", className = "com.sample.impl.jaxws.SubtractResponse")
	public int subtract(@WebParam(name = "arg0", targetNamespace = "http://www.example.org/calculatorservice/")
	int arg0, @WebParam(name = "arg1", targetNamespace = "http://www.example.org/calculatorservice/")
	int arg1);

//	/**
//	 * 
//	 * @param arg0
//	 * @param arg1
//	 * @return returns int
//	 */
//	@WebMethod
//	@WebResult(targetNamespace = "")
//	@RequestWrapper(localName = "multiply", targetNamespace = "http://www.example.org/calculatorservice/", className = "com.myeclipseide.ws.Multiply")
//	@ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://www.example.org/calculatorservice/", className = "com.myeclipseide.ws.MultiplyResponse")
//	public int multiply(@WebParam(name = "arg0", targetNamespace = "")
//	int arg0, @WebParam(name = "arg1", targetNamespace = "")
//	int arg1);
//
//	/**
//	 * 
//	 * @param arg0
//	 * @param arg1
//	 * @return returns int
//	 */
//	@WebMethod
//	@WebResult(targetNamespace = "")
//	@RequestWrapper(localName = "divide", targetNamespace = "http://www.example.org/calculatorservice/", className = "com.myeclipseide.ws.Divide")
//	@ResponseWrapper(localName = "divideResponse", targetNamespace = "http://www.example.org/calculatorservice/", className = "com.myeclipseide.ws.DivideResponse")
//	public int divide(@WebParam(name = "arg0", targetNamespace = "")
//	int arg0, @WebParam(name = "arg1", targetNamespace = "")
//	int arg1);

}
